# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HaCareem-3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HaCareem-3

pod 'AFNetworking', '~> 2.2'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Reachability'
pod 'FormatterKit'
pod 'Google-Maps-iOS-Utils'

  target 'HaCareem-3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HaCareem-3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
